/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AppRouteImport } from './routes/_app'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as LoginUnitRouteImport } from './routes/login.$unit'
import { Route as PublicUnitUsahaRouteImport } from './routes/_public.unit-usaha'
import { Route as PublicTransparansiRouteImport } from './routes/_public.transparansi'
import { Route as PublicTentangRouteImport } from './routes/_public.tentang'
import { Route as PublicKontakRouteImport } from './routes/_public.kontak'
import { Route as AppUspRouteImport } from './routes/_app.usp'
import { Route as AppTransferAntarEntitasRouteImport } from './routes/_app.transfer-antar-entitas'
import { Route as AppPengaturanRouteImport } from './routes/_app.pengaturan'
import { Route as AppLaporanPusatRouteImport } from './routes/_app.laporan-pusat'
import { Route as AppJurnalKoreksiRouteImport } from './routes/_app.jurnal-koreksi'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppDagangRouteImport } from './routes/_app.dagang'
import { Route as AppCoaRouteImport } from './routes/_app.coa'
import { Route as AppCatatKegiatanRouteImport } from './routes/_app.catat-kegiatan'
import { Route as AppAsetRouteImport } from './routes/_app.aset'
import { Route as AppUspIndexRouteImport } from './routes/_app.usp.index'
import { Route as AppPengaturanIndexRouteImport } from './routes/_app.pengaturan.index'
import { Route as AppDagangIndexRouteImport } from './routes/_app.dagang.index'
import { Route as AppUspTransferRouteImport } from './routes/_app.usp.transfer'
import { Route as AppUspPinjamanRouteImport } from './routes/_app.usp.pinjaman'
import { Route as AppUspLaporanRouteImport } from './routes/_app.usp.laporan'
import { Route as AppUspKegiatanRouteImport } from './routes/_app.usp.kegiatan'
import { Route as AppUspJurnalKoreksiRouteImport } from './routes/_app.usp.jurnal-koreksi'
import { Route as AppUspAsetRouteImport } from './routes/_app.usp.aset'
import { Route as AppPusatKegiatanRouteImport } from './routes/_app.pusat.kegiatan'
import { Route as AppPengaturanUsersRouteImport } from './routes/_app.pengaturan.users'
import { Route as AppPengaturanBagiHasilRouteImport } from './routes/_app.pengaturan.bagi-hasil'
import { Route as AppLaporanRekonsiliasiRkRouteImport } from './routes/_app.laporan.rekonsiliasi-rk'
import { Route as AppLaporanNeracaPusatRouteImport } from './routes/_app.laporan.neraca-pusat'
import { Route as AppLaporanNeracaKonsolidasiRouteImport } from './routes/_app.laporan.neraca-konsolidasi'
import { Route as AppLaporanLabaRugiRouteImport } from './routes/_app.laporan.laba-rugi'
import { Route as AppLaporanBukuBesarPusatRouteImport } from './routes/_app.laporan.buku-besar-pusat'
import { Route as AppLaporanBukuBesarKonsolidasiRouteImport } from './routes/_app.laporan.buku-besar-konsolidasi'
import { Route as AppLaporanBagiHasilRouteImport } from './routes/_app.laporan.bagi-hasil'
import { Route as AppDagangTransferRouteImport } from './routes/_app.dagang.transfer'
import { Route as AppDagangStokRouteImport } from './routes/_app.dagang.stok'
import { Route as AppDagangLaporanRouteImport } from './routes/_app.dagang.laporan'
import { Route as AppDagangKegiatanRouteImport } from './routes/_app.dagang.kegiatan'
import { Route as AppDagangJurnalKoreksiRouteImport } from './routes/_app.dagang.jurnal-koreksi'
import { Route as AppDagangAsetRouteImport } from './routes/_app.dagang.aset'
import { Route as AppUspLaporanIndexRouteImport } from './routes/_app.usp.laporan.index'
import { Route as AppUspKegiatanIndexRouteImport } from './routes/_app.usp.kegiatan.index'
import { Route as AppDagangLaporanIndexRouteImport } from './routes/_app.dagang.laporan.index'
import { Route as AppDagangKegiatanIndexRouteImport } from './routes/_app.dagang.kegiatan.index'
import { Route as AppUspLaporanRekonsiliasiRkRouteImport } from './routes/_app.usp.laporan.rekonsiliasi-rk'
import { Route as AppUspLaporanNeracaRouteImport } from './routes/_app.usp.laporan.neraca'
import { Route as AppUspLaporanLabaRugiRouteImport } from './routes/_app.usp.laporan.laba-rugi'
import { Route as AppUspLaporanBukuBesarRouteImport } from './routes/_app.usp.laporan.buku-besar'
import { Route as AppUspLaporanBagiHasilRouteImport } from './routes/_app.usp.laporan.bagi-hasil'
import { Route as AppUspKegiatanPenyertaanModalRouteImport } from './routes/_app.usp.kegiatan.penyertaan-modal'
import { Route as AppUspKegiatanPengeluaranRouteImport } from './routes/_app.usp.kegiatan.pengeluaran'
import { Route as AppUspKegiatanPenerimaanKasRouteImport } from './routes/_app.usp.kegiatan.penerimaan-kas'
import { Route as AppUspKegiatanPencairanRouteImport } from './routes/_app.usp.kegiatan.pencairan'
import { Route as AppUspKegiatanDendaRouteImport } from './routes/_app.usp.kegiatan.denda'
import { Route as AppUspKegiatanBelanjaAsetRouteImport } from './routes/_app.usp.kegiatan.belanja-aset'
import { Route as AppUspKegiatanBebanRouteImport } from './routes/_app.usp.kegiatan.beban'
import { Route as AppUspKegiatanAngsuranRouteImport } from './routes/_app.usp.kegiatan.angsuran'
import { Route as AppDagangLaporanRekonsiliasiRkRouteImport } from './routes/_app.dagang.laporan.rekonsiliasi-rk'
import { Route as AppDagangLaporanNeracaRouteImport } from './routes/_app.dagang.laporan.neraca'
import { Route as AppDagangLaporanLabaRugiRouteImport } from './routes/_app.dagang.laporan.laba-rugi'
import { Route as AppDagangLaporanBukuBesarRouteImport } from './routes/_app.dagang.laporan.buku-besar'
import { Route as AppDagangLaporanBagiHasilRouteImport } from './routes/_app.dagang.laporan.bagi-hasil'
import { Route as AppDagangKegiatanPenjualanTunaiRouteImport } from './routes/_app.dagang.kegiatan.penjualan-tunai'
import { Route as AppDagangKegiatanPenjualanKreditRouteImport } from './routes/_app.dagang.kegiatan.penjualan-kredit'
import { Route as AppDagangKegiatanPengeluaranRouteImport } from './routes/_app.dagang.kegiatan.pengeluaran'
import { Route as AppDagangKegiatanPenerimaanPiutangRouteImport } from './routes/_app.dagang.kegiatan.penerimaan-piutang'
import { Route as AppDagangKegiatanPenerimaanKasRouteImport } from './routes/_app.dagang.kegiatan.penerimaan-kas'
import { Route as AppDagangKegiatanPembelianTunaiRouteImport } from './routes/_app.dagang.kegiatan.pembelian-tunai'
import { Route as AppDagangKegiatanPembelianKreditRouteImport } from './routes/_app.dagang.kegiatan.pembelian-kredit'
import { Route as AppDagangKegiatanPembayaranUtangRouteImport } from './routes/_app.dagang.kegiatan.pembayaran-utang'
import { Route as AppDagangKegiatanBelanjaAsetRouteImport } from './routes/_app.dagang.kegiatan.belanja-aset'
import { Route as AppDagangKegiatanBebanRouteImport } from './routes/_app.dagang.kegiatan.beban'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const LoginUnitRoute = LoginUnitRouteImport.update({
  id: '/$unit',
  path: '/$unit',
  getParentRoute: () => LoginRoute,
} as any)
const PublicUnitUsahaRoute = PublicUnitUsahaRouteImport.update({
  id: '/unit-usaha',
  path: '/unit-usaha',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTransparansiRoute = PublicTransparansiRouteImport.update({
  id: '/transparansi',
  path: '/transparansi',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTentangRoute = PublicTentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => PublicRoute,
} as any)
const PublicKontakRoute = PublicKontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => PublicRoute,
} as any)
const AppUspRoute = AppUspRouteImport.update({
  id: '/usp',
  path: '/usp',
  getParentRoute: () => AppRoute,
} as any)
const AppTransferAntarEntitasRoute = AppTransferAntarEntitasRouteImport.update({
  id: '/transfer-antar-entitas',
  path: '/transfer-antar-entitas',
  getParentRoute: () => AppRoute,
} as any)
const AppPengaturanRoute = AppPengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => AppRoute,
} as any)
const AppLaporanPusatRoute = AppLaporanPusatRouteImport.update({
  id: '/laporan-pusat',
  path: '/laporan-pusat',
  getParentRoute: () => AppRoute,
} as any)
const AppJurnalKoreksiRoute = AppJurnalKoreksiRouteImport.update({
  id: '/jurnal-koreksi',
  path: '/jurnal-koreksi',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDagangRoute = AppDagangRouteImport.update({
  id: '/dagang',
  path: '/dagang',
  getParentRoute: () => AppRoute,
} as any)
const AppCoaRoute = AppCoaRouteImport.update({
  id: '/coa',
  path: '/coa',
  getParentRoute: () => AppRoute,
} as any)
const AppCatatKegiatanRoute = AppCatatKegiatanRouteImport.update({
  id: '/catat-kegiatan',
  path: '/catat-kegiatan',
  getParentRoute: () => AppRoute,
} as any)
const AppAsetRoute = AppAsetRouteImport.update({
  id: '/aset',
  path: '/aset',
  getParentRoute: () => AppRoute,
} as any)
const AppUspIndexRoute = AppUspIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppUspRoute,
} as any)
const AppPengaturanIndexRoute = AppPengaturanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPengaturanRoute,
} as any)
const AppDagangIndexRoute = AppDagangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDagangRoute,
} as any)
const AppUspTransferRoute = AppUspTransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => AppUspRoute,
} as any)
const AppUspPinjamanRoute = AppUspPinjamanRouteImport.update({
  id: '/pinjaman',
  path: '/pinjaman',
  getParentRoute: () => AppUspRoute,
} as any)
const AppUspLaporanRoute = AppUspLaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => AppUspRoute,
} as any)
const AppUspKegiatanRoute = AppUspKegiatanRouteImport.update({
  id: '/kegiatan',
  path: '/kegiatan',
  getParentRoute: () => AppUspRoute,
} as any)
const AppUspJurnalKoreksiRoute = AppUspJurnalKoreksiRouteImport.update({
  id: '/jurnal-koreksi',
  path: '/jurnal-koreksi',
  getParentRoute: () => AppUspRoute,
} as any)
const AppUspAsetRoute = AppUspAsetRouteImport.update({
  id: '/aset',
  path: '/aset',
  getParentRoute: () => AppUspRoute,
} as any)
const AppPusatKegiatanRoute = AppPusatKegiatanRouteImport.update({
  id: '/pusat/kegiatan',
  path: '/pusat/kegiatan',
  getParentRoute: () => AppRoute,
} as any)
const AppPengaturanUsersRoute = AppPengaturanUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppPengaturanRoute,
} as any)
const AppPengaturanBagiHasilRoute = AppPengaturanBagiHasilRouteImport.update({
  id: '/bagi-hasil',
  path: '/bagi-hasil',
  getParentRoute: () => AppPengaturanRoute,
} as any)
const AppLaporanRekonsiliasiRkRoute =
  AppLaporanRekonsiliasiRkRouteImport.update({
    id: '/laporan/rekonsiliasi-rk',
    path: '/laporan/rekonsiliasi-rk',
    getParentRoute: () => AppRoute,
  } as any)
const AppLaporanNeracaPusatRoute = AppLaporanNeracaPusatRouteImport.update({
  id: '/laporan/neraca-pusat',
  path: '/laporan/neraca-pusat',
  getParentRoute: () => AppRoute,
} as any)
const AppLaporanNeracaKonsolidasiRoute =
  AppLaporanNeracaKonsolidasiRouteImport.update({
    id: '/laporan/neraca-konsolidasi',
    path: '/laporan/neraca-konsolidasi',
    getParentRoute: () => AppRoute,
  } as any)
const AppLaporanLabaRugiRoute = AppLaporanLabaRugiRouteImport.update({
  id: '/laporan/laba-rugi',
  path: '/laporan/laba-rugi',
  getParentRoute: () => AppRoute,
} as any)
const AppLaporanBukuBesarPusatRoute =
  AppLaporanBukuBesarPusatRouteImport.update({
    id: '/laporan/buku-besar-pusat',
    path: '/laporan/buku-besar-pusat',
    getParentRoute: () => AppRoute,
  } as any)
const AppLaporanBukuBesarKonsolidasiRoute =
  AppLaporanBukuBesarKonsolidasiRouteImport.update({
    id: '/laporan/buku-besar-konsolidasi',
    path: '/laporan/buku-besar-konsolidasi',
    getParentRoute: () => AppRoute,
  } as any)
const AppLaporanBagiHasilRoute = AppLaporanBagiHasilRouteImport.update({
  id: '/laporan/bagi-hasil',
  path: '/laporan/bagi-hasil',
  getParentRoute: () => AppRoute,
} as any)
const AppDagangTransferRoute = AppDagangTransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => AppDagangRoute,
} as any)
const AppDagangStokRoute = AppDagangStokRouteImport.update({
  id: '/stok',
  path: '/stok',
  getParentRoute: () => AppDagangRoute,
} as any)
const AppDagangLaporanRoute = AppDagangLaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => AppDagangRoute,
} as any)
const AppDagangKegiatanRoute = AppDagangKegiatanRouteImport.update({
  id: '/kegiatan',
  path: '/kegiatan',
  getParentRoute: () => AppDagangRoute,
} as any)
const AppDagangJurnalKoreksiRoute = AppDagangJurnalKoreksiRouteImport.update({
  id: '/jurnal-koreksi',
  path: '/jurnal-koreksi',
  getParentRoute: () => AppDagangRoute,
} as any)
const AppDagangAsetRoute = AppDagangAsetRouteImport.update({
  id: '/aset',
  path: '/aset',
  getParentRoute: () => AppDagangRoute,
} as any)
const AppUspLaporanIndexRoute = AppUspLaporanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppUspLaporanRoute,
} as any)
const AppUspKegiatanIndexRoute = AppUspKegiatanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppUspKegiatanRoute,
} as any)
const AppDagangLaporanIndexRoute = AppDagangLaporanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDagangLaporanRoute,
} as any)
const AppDagangKegiatanIndexRoute = AppDagangKegiatanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDagangKegiatanRoute,
} as any)
const AppUspLaporanRekonsiliasiRkRoute =
  AppUspLaporanRekonsiliasiRkRouteImport.update({
    id: '/rekonsiliasi-rk',
    path: '/rekonsiliasi-rk',
    getParentRoute: () => AppUspLaporanRoute,
  } as any)
const AppUspLaporanNeracaRoute = AppUspLaporanNeracaRouteImport.update({
  id: '/neraca',
  path: '/neraca',
  getParentRoute: () => AppUspLaporanRoute,
} as any)
const AppUspLaporanLabaRugiRoute = AppUspLaporanLabaRugiRouteImport.update({
  id: '/laba-rugi',
  path: '/laba-rugi',
  getParentRoute: () => AppUspLaporanRoute,
} as any)
const AppUspLaporanBukuBesarRoute = AppUspLaporanBukuBesarRouteImport.update({
  id: '/buku-besar',
  path: '/buku-besar',
  getParentRoute: () => AppUspLaporanRoute,
} as any)
const AppUspLaporanBagiHasilRoute = AppUspLaporanBagiHasilRouteImport.update({
  id: '/bagi-hasil',
  path: '/bagi-hasil',
  getParentRoute: () => AppUspLaporanRoute,
} as any)
const AppUspKegiatanPenyertaanModalRoute =
  AppUspKegiatanPenyertaanModalRouteImport.update({
    id: '/penyertaan-modal',
    path: '/penyertaan-modal',
    getParentRoute: () => AppUspKegiatanRoute,
  } as any)
const AppUspKegiatanPengeluaranRoute =
  AppUspKegiatanPengeluaranRouteImport.update({
    id: '/pengeluaran',
    path: '/pengeluaran',
    getParentRoute: () => AppUspKegiatanRoute,
  } as any)
const AppUspKegiatanPenerimaanKasRoute =
  AppUspKegiatanPenerimaanKasRouteImport.update({
    id: '/penerimaan-kas',
    path: '/penerimaan-kas',
    getParentRoute: () => AppUspKegiatanRoute,
  } as any)
const AppUspKegiatanPencairanRoute = AppUspKegiatanPencairanRouteImport.update({
  id: '/pencairan',
  path: '/pencairan',
  getParentRoute: () => AppUspKegiatanRoute,
} as any)
const AppUspKegiatanDendaRoute = AppUspKegiatanDendaRouteImport.update({
  id: '/denda',
  path: '/denda',
  getParentRoute: () => AppUspKegiatanRoute,
} as any)
const AppUspKegiatanBelanjaAsetRoute =
  AppUspKegiatanBelanjaAsetRouteImport.update({
    id: '/belanja-aset',
    path: '/belanja-aset',
    getParentRoute: () => AppUspKegiatanRoute,
  } as any)
const AppUspKegiatanBebanRoute = AppUspKegiatanBebanRouteImport.update({
  id: '/beban',
  path: '/beban',
  getParentRoute: () => AppUspKegiatanRoute,
} as any)
const AppUspKegiatanAngsuranRoute = AppUspKegiatanAngsuranRouteImport.update({
  id: '/angsuran',
  path: '/angsuran',
  getParentRoute: () => AppUspKegiatanRoute,
} as any)
const AppDagangLaporanRekonsiliasiRkRoute =
  AppDagangLaporanRekonsiliasiRkRouteImport.update({
    id: '/rekonsiliasi-rk',
    path: '/rekonsiliasi-rk',
    getParentRoute: () => AppDagangLaporanRoute,
  } as any)
const AppDagangLaporanNeracaRoute = AppDagangLaporanNeracaRouteImport.update({
  id: '/neraca',
  path: '/neraca',
  getParentRoute: () => AppDagangLaporanRoute,
} as any)
const AppDagangLaporanLabaRugiRoute =
  AppDagangLaporanLabaRugiRouteImport.update({
    id: '/laba-rugi',
    path: '/laba-rugi',
    getParentRoute: () => AppDagangLaporanRoute,
  } as any)
const AppDagangLaporanBukuBesarRoute =
  AppDagangLaporanBukuBesarRouteImport.update({
    id: '/buku-besar',
    path: '/buku-besar',
    getParentRoute: () => AppDagangLaporanRoute,
  } as any)
const AppDagangLaporanBagiHasilRoute =
  AppDagangLaporanBagiHasilRouteImport.update({
    id: '/bagi-hasil',
    path: '/bagi-hasil',
    getParentRoute: () => AppDagangLaporanRoute,
  } as any)
const AppDagangKegiatanPenjualanTunaiRoute =
  AppDagangKegiatanPenjualanTunaiRouteImport.update({
    id: '/penjualan-tunai',
    path: '/penjualan-tunai',
    getParentRoute: () => AppDagangKegiatanRoute,
  } as any)
const AppDagangKegiatanPenjualanKreditRoute =
  AppDagangKegiatanPenjualanKreditRouteImport.update({
    id: '/penjualan-kredit',
    path: '/penjualan-kredit',
    getParentRoute: () => AppDagangKegiatanRoute,
  } as any)
const AppDagangKegiatanPengeluaranRoute =
  AppDagangKegiatanPengeluaranRouteImport.update({
    id: '/pengeluaran',
    path: '/pengeluaran',
    getParentRoute: () => AppDagangKegiatanRoute,
  } as any)
const AppDagangKegiatanPenerimaanPiutangRoute =
  AppDagangKegiatanPenerimaanPiutangRouteImport.update({
    id: '/penerimaan-piutang',
    path: '/penerimaan-piutang',
    getParentRoute: () => AppDagangKegiatanRoute,
  } as any)
const AppDagangKegiatanPenerimaanKasRoute =
  AppDagangKegiatanPenerimaanKasRouteImport.update({
    id: '/penerimaan-kas',
    path: '/penerimaan-kas',
    getParentRoute: () => AppDagangKegiatanRoute,
  } as any)
const AppDagangKegiatanPembelianTunaiRoute =
  AppDagangKegiatanPembelianTunaiRouteImport.update({
    id: '/pembelian-tunai',
    path: '/pembelian-tunai',
    getParentRoute: () => AppDagangKegiatanRoute,
  } as any)
const AppDagangKegiatanPembelianKreditRoute =
  AppDagangKegiatanPembelianKreditRouteImport.update({
    id: '/pembelian-kredit',
    path: '/pembelian-kredit',
    getParentRoute: () => AppDagangKegiatanRoute,
  } as any)
const AppDagangKegiatanPembayaranUtangRoute =
  AppDagangKegiatanPembayaranUtangRouteImport.update({
    id: '/pembayaran-utang',
    path: '/pembayaran-utang',
    getParentRoute: () => AppDagangKegiatanRoute,
  } as any)
const AppDagangKegiatanBelanjaAsetRoute =
  AppDagangKegiatanBelanjaAsetRouteImport.update({
    id: '/belanja-aset',
    path: '/belanja-aset',
    getParentRoute: () => AppDagangKegiatanRoute,
  } as any)
const AppDagangKegiatanBebanRoute = AppDagangKegiatanBebanRouteImport.update({
  id: '/beban',
  path: '/beban',
  getParentRoute: () => AppDagangKegiatanRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/login': typeof LoginRouteWithChildren
  '/aset': typeof AppAsetRoute
  '/catat-kegiatan': typeof AppCatatKegiatanRoute
  '/coa': typeof AppCoaRoute
  '/dagang': typeof AppDagangRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/jurnal-koreksi': typeof AppJurnalKoreksiRoute
  '/laporan-pusat': typeof AppLaporanPusatRoute
  '/pengaturan': typeof AppPengaturanRouteWithChildren
  '/transfer-antar-entitas': typeof AppTransferAntarEntitasRoute
  '/usp': typeof AppUspRouteWithChildren
  '/kontak': typeof PublicKontakRoute
  '/tentang': typeof PublicTentangRoute
  '/transparansi': typeof PublicTransparansiRoute
  '/unit-usaha': typeof PublicUnitUsahaRoute
  '/login/$unit': typeof LoginUnitRoute
  '/dagang/aset': typeof AppDagangAsetRoute
  '/dagang/jurnal-koreksi': typeof AppDagangJurnalKoreksiRoute
  '/dagang/kegiatan': typeof AppDagangKegiatanRouteWithChildren
  '/dagang/laporan': typeof AppDagangLaporanRouteWithChildren
  '/dagang/stok': typeof AppDagangStokRoute
  '/dagang/transfer': typeof AppDagangTransferRoute
  '/laporan/bagi-hasil': typeof AppLaporanBagiHasilRoute
  '/laporan/buku-besar-konsolidasi': typeof AppLaporanBukuBesarKonsolidasiRoute
  '/laporan/buku-besar-pusat': typeof AppLaporanBukuBesarPusatRoute
  '/laporan/laba-rugi': typeof AppLaporanLabaRugiRoute
  '/laporan/neraca-konsolidasi': typeof AppLaporanNeracaKonsolidasiRoute
  '/laporan/neraca-pusat': typeof AppLaporanNeracaPusatRoute
  '/laporan/rekonsiliasi-rk': typeof AppLaporanRekonsiliasiRkRoute
  '/pengaturan/bagi-hasil': typeof AppPengaturanBagiHasilRoute
  '/pengaturan/users': typeof AppPengaturanUsersRoute
  '/pusat/kegiatan': typeof AppPusatKegiatanRoute
  '/usp/aset': typeof AppUspAsetRoute
  '/usp/jurnal-koreksi': typeof AppUspJurnalKoreksiRoute
  '/usp/kegiatan': typeof AppUspKegiatanRouteWithChildren
  '/usp/laporan': typeof AppUspLaporanRouteWithChildren
  '/usp/pinjaman': typeof AppUspPinjamanRoute
  '/usp/transfer': typeof AppUspTransferRoute
  '/dagang/': typeof AppDagangIndexRoute
  '/pengaturan/': typeof AppPengaturanIndexRoute
  '/usp/': typeof AppUspIndexRoute
  '/dagang/kegiatan/beban': typeof AppDagangKegiatanBebanRoute
  '/dagang/kegiatan/belanja-aset': typeof AppDagangKegiatanBelanjaAsetRoute
  '/dagang/kegiatan/pembayaran-utang': typeof AppDagangKegiatanPembayaranUtangRoute
  '/dagang/kegiatan/pembelian-kredit': typeof AppDagangKegiatanPembelianKreditRoute
  '/dagang/kegiatan/pembelian-tunai': typeof AppDagangKegiatanPembelianTunaiRoute
  '/dagang/kegiatan/penerimaan-kas': typeof AppDagangKegiatanPenerimaanKasRoute
  '/dagang/kegiatan/penerimaan-piutang': typeof AppDagangKegiatanPenerimaanPiutangRoute
  '/dagang/kegiatan/pengeluaran': typeof AppDagangKegiatanPengeluaranRoute
  '/dagang/kegiatan/penjualan-kredit': typeof AppDagangKegiatanPenjualanKreditRoute
  '/dagang/kegiatan/penjualan-tunai': typeof AppDagangKegiatanPenjualanTunaiRoute
  '/dagang/laporan/bagi-hasil': typeof AppDagangLaporanBagiHasilRoute
  '/dagang/laporan/buku-besar': typeof AppDagangLaporanBukuBesarRoute
  '/dagang/laporan/laba-rugi': typeof AppDagangLaporanLabaRugiRoute
  '/dagang/laporan/neraca': typeof AppDagangLaporanNeracaRoute
  '/dagang/laporan/rekonsiliasi-rk': typeof AppDagangLaporanRekonsiliasiRkRoute
  '/usp/kegiatan/angsuran': typeof AppUspKegiatanAngsuranRoute
  '/usp/kegiatan/beban': typeof AppUspKegiatanBebanRoute
  '/usp/kegiatan/belanja-aset': typeof AppUspKegiatanBelanjaAsetRoute
  '/usp/kegiatan/denda': typeof AppUspKegiatanDendaRoute
  '/usp/kegiatan/pencairan': typeof AppUspKegiatanPencairanRoute
  '/usp/kegiatan/penerimaan-kas': typeof AppUspKegiatanPenerimaanKasRoute
  '/usp/kegiatan/pengeluaran': typeof AppUspKegiatanPengeluaranRoute
  '/usp/kegiatan/penyertaan-modal': typeof AppUspKegiatanPenyertaanModalRoute
  '/usp/laporan/bagi-hasil': typeof AppUspLaporanBagiHasilRoute
  '/usp/laporan/buku-besar': typeof AppUspLaporanBukuBesarRoute
  '/usp/laporan/laba-rugi': typeof AppUspLaporanLabaRugiRoute
  '/usp/laporan/neraca': typeof AppUspLaporanNeracaRoute
  '/usp/laporan/rekonsiliasi-rk': typeof AppUspLaporanRekonsiliasiRkRoute
  '/dagang/kegiatan/': typeof AppDagangKegiatanIndexRoute
  '/dagang/laporan/': typeof AppDagangLaporanIndexRoute
  '/usp/kegiatan/': typeof AppUspKegiatanIndexRoute
  '/usp/laporan/': typeof AppUspLaporanIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/login': typeof LoginRouteWithChildren
  '/aset': typeof AppAsetRoute
  '/catat-kegiatan': typeof AppCatatKegiatanRoute
  '/coa': typeof AppCoaRoute
  '/dashboard': typeof AppDashboardRoute
  '/jurnal-koreksi': typeof AppJurnalKoreksiRoute
  '/laporan-pusat': typeof AppLaporanPusatRoute
  '/transfer-antar-entitas': typeof AppTransferAntarEntitasRoute
  '/kontak': typeof PublicKontakRoute
  '/tentang': typeof PublicTentangRoute
  '/transparansi': typeof PublicTransparansiRoute
  '/unit-usaha': typeof PublicUnitUsahaRoute
  '/login/$unit': typeof LoginUnitRoute
  '/dagang/aset': typeof AppDagangAsetRoute
  '/dagang/jurnal-koreksi': typeof AppDagangJurnalKoreksiRoute
  '/dagang/stok': typeof AppDagangStokRoute
  '/dagang/transfer': typeof AppDagangTransferRoute
  '/laporan/bagi-hasil': typeof AppLaporanBagiHasilRoute
  '/laporan/buku-besar-konsolidasi': typeof AppLaporanBukuBesarKonsolidasiRoute
  '/laporan/buku-besar-pusat': typeof AppLaporanBukuBesarPusatRoute
  '/laporan/laba-rugi': typeof AppLaporanLabaRugiRoute
  '/laporan/neraca-konsolidasi': typeof AppLaporanNeracaKonsolidasiRoute
  '/laporan/neraca-pusat': typeof AppLaporanNeracaPusatRoute
  '/laporan/rekonsiliasi-rk': typeof AppLaporanRekonsiliasiRkRoute
  '/pengaturan/bagi-hasil': typeof AppPengaturanBagiHasilRoute
  '/pengaturan/users': typeof AppPengaturanUsersRoute
  '/pusat/kegiatan': typeof AppPusatKegiatanRoute
  '/usp/aset': typeof AppUspAsetRoute
  '/usp/jurnal-koreksi': typeof AppUspJurnalKoreksiRoute
  '/usp/pinjaman': typeof AppUspPinjamanRoute
  '/usp/transfer': typeof AppUspTransferRoute
  '/dagang': typeof AppDagangIndexRoute
  '/pengaturan': typeof AppPengaturanIndexRoute
  '/usp': typeof AppUspIndexRoute
  '/dagang/kegiatan/beban': typeof AppDagangKegiatanBebanRoute
  '/dagang/kegiatan/belanja-aset': typeof AppDagangKegiatanBelanjaAsetRoute
  '/dagang/kegiatan/pembayaran-utang': typeof AppDagangKegiatanPembayaranUtangRoute
  '/dagang/kegiatan/pembelian-kredit': typeof AppDagangKegiatanPembelianKreditRoute
  '/dagang/kegiatan/pembelian-tunai': typeof AppDagangKegiatanPembelianTunaiRoute
  '/dagang/kegiatan/penerimaan-kas': typeof AppDagangKegiatanPenerimaanKasRoute
  '/dagang/kegiatan/penerimaan-piutang': typeof AppDagangKegiatanPenerimaanPiutangRoute
  '/dagang/kegiatan/pengeluaran': typeof AppDagangKegiatanPengeluaranRoute
  '/dagang/kegiatan/penjualan-kredit': typeof AppDagangKegiatanPenjualanKreditRoute
  '/dagang/kegiatan/penjualan-tunai': typeof AppDagangKegiatanPenjualanTunaiRoute
  '/dagang/laporan/bagi-hasil': typeof AppDagangLaporanBagiHasilRoute
  '/dagang/laporan/buku-besar': typeof AppDagangLaporanBukuBesarRoute
  '/dagang/laporan/laba-rugi': typeof AppDagangLaporanLabaRugiRoute
  '/dagang/laporan/neraca': typeof AppDagangLaporanNeracaRoute
  '/dagang/laporan/rekonsiliasi-rk': typeof AppDagangLaporanRekonsiliasiRkRoute
  '/usp/kegiatan/angsuran': typeof AppUspKegiatanAngsuranRoute
  '/usp/kegiatan/beban': typeof AppUspKegiatanBebanRoute
  '/usp/kegiatan/belanja-aset': typeof AppUspKegiatanBelanjaAsetRoute
  '/usp/kegiatan/denda': typeof AppUspKegiatanDendaRoute
  '/usp/kegiatan/pencairan': typeof AppUspKegiatanPencairanRoute
  '/usp/kegiatan/penerimaan-kas': typeof AppUspKegiatanPenerimaanKasRoute
  '/usp/kegiatan/pengeluaran': typeof AppUspKegiatanPengeluaranRoute
  '/usp/kegiatan/penyertaan-modal': typeof AppUspKegiatanPenyertaanModalRoute
  '/usp/laporan/bagi-hasil': typeof AppUspLaporanBagiHasilRoute
  '/usp/laporan/buku-besar': typeof AppUspLaporanBukuBesarRoute
  '/usp/laporan/laba-rugi': typeof AppUspLaporanLabaRugiRoute
  '/usp/laporan/neraca': typeof AppUspLaporanNeracaRoute
  '/usp/laporan/rekonsiliasi-rk': typeof AppUspLaporanRekonsiliasiRkRoute
  '/dagang/kegiatan': typeof AppDagangKegiatanIndexRoute
  '/dagang/laporan': typeof AppDagangLaporanIndexRoute
  '/usp/kegiatan': typeof AppUspKegiatanIndexRoute
  '/usp/laporan': typeof AppUspLaporanIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/_app/aset': typeof AppAsetRoute
  '/_app/catat-kegiatan': typeof AppCatatKegiatanRoute
  '/_app/coa': typeof AppCoaRoute
  '/_app/dagang': typeof AppDagangRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/jurnal-koreksi': typeof AppJurnalKoreksiRoute
  '/_app/laporan-pusat': typeof AppLaporanPusatRoute
  '/_app/pengaturan': typeof AppPengaturanRouteWithChildren
  '/_app/transfer-antar-entitas': typeof AppTransferAntarEntitasRoute
  '/_app/usp': typeof AppUspRouteWithChildren
  '/_public/kontak': typeof PublicKontakRoute
  '/_public/tentang': typeof PublicTentangRoute
  '/_public/transparansi': typeof PublicTransparansiRoute
  '/_public/unit-usaha': typeof PublicUnitUsahaRoute
  '/login/$unit': typeof LoginUnitRoute
  '/_public/': typeof PublicIndexRoute
  '/_app/dagang/aset': typeof AppDagangAsetRoute
  '/_app/dagang/jurnal-koreksi': typeof AppDagangJurnalKoreksiRoute
  '/_app/dagang/kegiatan': typeof AppDagangKegiatanRouteWithChildren
  '/_app/dagang/laporan': typeof AppDagangLaporanRouteWithChildren
  '/_app/dagang/stok': typeof AppDagangStokRoute
  '/_app/dagang/transfer': typeof AppDagangTransferRoute
  '/_app/laporan/bagi-hasil': typeof AppLaporanBagiHasilRoute
  '/_app/laporan/buku-besar-konsolidasi': typeof AppLaporanBukuBesarKonsolidasiRoute
  '/_app/laporan/buku-besar-pusat': typeof AppLaporanBukuBesarPusatRoute
  '/_app/laporan/laba-rugi': typeof AppLaporanLabaRugiRoute
  '/_app/laporan/neraca-konsolidasi': typeof AppLaporanNeracaKonsolidasiRoute
  '/_app/laporan/neraca-pusat': typeof AppLaporanNeracaPusatRoute
  '/_app/laporan/rekonsiliasi-rk': typeof AppLaporanRekonsiliasiRkRoute
  '/_app/pengaturan/bagi-hasil': typeof AppPengaturanBagiHasilRoute
  '/_app/pengaturan/users': typeof AppPengaturanUsersRoute
  '/_app/pusat/kegiatan': typeof AppPusatKegiatanRoute
  '/_app/usp/aset': typeof AppUspAsetRoute
  '/_app/usp/jurnal-koreksi': typeof AppUspJurnalKoreksiRoute
  '/_app/usp/kegiatan': typeof AppUspKegiatanRouteWithChildren
  '/_app/usp/laporan': typeof AppUspLaporanRouteWithChildren
  '/_app/usp/pinjaman': typeof AppUspPinjamanRoute
  '/_app/usp/transfer': typeof AppUspTransferRoute
  '/_app/dagang/': typeof AppDagangIndexRoute
  '/_app/pengaturan/': typeof AppPengaturanIndexRoute
  '/_app/usp/': typeof AppUspIndexRoute
  '/_app/dagang/kegiatan/beban': typeof AppDagangKegiatanBebanRoute
  '/_app/dagang/kegiatan/belanja-aset': typeof AppDagangKegiatanBelanjaAsetRoute
  '/_app/dagang/kegiatan/pembayaran-utang': typeof AppDagangKegiatanPembayaranUtangRoute
  '/_app/dagang/kegiatan/pembelian-kredit': typeof AppDagangKegiatanPembelianKreditRoute
  '/_app/dagang/kegiatan/pembelian-tunai': typeof AppDagangKegiatanPembelianTunaiRoute
  '/_app/dagang/kegiatan/penerimaan-kas': typeof AppDagangKegiatanPenerimaanKasRoute
  '/_app/dagang/kegiatan/penerimaan-piutang': typeof AppDagangKegiatanPenerimaanPiutangRoute
  '/_app/dagang/kegiatan/pengeluaran': typeof AppDagangKegiatanPengeluaranRoute
  '/_app/dagang/kegiatan/penjualan-kredit': typeof AppDagangKegiatanPenjualanKreditRoute
  '/_app/dagang/kegiatan/penjualan-tunai': typeof AppDagangKegiatanPenjualanTunaiRoute
  '/_app/dagang/laporan/bagi-hasil': typeof AppDagangLaporanBagiHasilRoute
  '/_app/dagang/laporan/buku-besar': typeof AppDagangLaporanBukuBesarRoute
  '/_app/dagang/laporan/laba-rugi': typeof AppDagangLaporanLabaRugiRoute
  '/_app/dagang/laporan/neraca': typeof AppDagangLaporanNeracaRoute
  '/_app/dagang/laporan/rekonsiliasi-rk': typeof AppDagangLaporanRekonsiliasiRkRoute
  '/_app/usp/kegiatan/angsuran': typeof AppUspKegiatanAngsuranRoute
  '/_app/usp/kegiatan/beban': typeof AppUspKegiatanBebanRoute
  '/_app/usp/kegiatan/belanja-aset': typeof AppUspKegiatanBelanjaAsetRoute
  '/_app/usp/kegiatan/denda': typeof AppUspKegiatanDendaRoute
  '/_app/usp/kegiatan/pencairan': typeof AppUspKegiatanPencairanRoute
  '/_app/usp/kegiatan/penerimaan-kas': typeof AppUspKegiatanPenerimaanKasRoute
  '/_app/usp/kegiatan/pengeluaran': typeof AppUspKegiatanPengeluaranRoute
  '/_app/usp/kegiatan/penyertaan-modal': typeof AppUspKegiatanPenyertaanModalRoute
  '/_app/usp/laporan/bagi-hasil': typeof AppUspLaporanBagiHasilRoute
  '/_app/usp/laporan/buku-besar': typeof AppUspLaporanBukuBesarRoute
  '/_app/usp/laporan/laba-rugi': typeof AppUspLaporanLabaRugiRoute
  '/_app/usp/laporan/neraca': typeof AppUspLaporanNeracaRoute
  '/_app/usp/laporan/rekonsiliasi-rk': typeof AppUspLaporanRekonsiliasiRkRoute
  '/_app/dagang/kegiatan/': typeof AppDagangKegiatanIndexRoute
  '/_app/dagang/laporan/': typeof AppDagangLaporanIndexRoute
  '/_app/usp/kegiatan/': typeof AppUspKegiatanIndexRoute
  '/_app/usp/laporan/': typeof AppUspLaporanIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/aset'
    | '/catat-kegiatan'
    | '/coa'
    | '/dagang'
    | '/dashboard'
    | '/jurnal-koreksi'
    | '/laporan-pusat'
    | '/pengaturan'
    | '/transfer-antar-entitas'
    | '/usp'
    | '/kontak'
    | '/tentang'
    | '/transparansi'
    | '/unit-usaha'
    | '/login/$unit'
    | '/dagang/aset'
    | '/dagang/jurnal-koreksi'
    | '/dagang/kegiatan'
    | '/dagang/laporan'
    | '/dagang/stok'
    | '/dagang/transfer'
    | '/laporan/bagi-hasil'
    | '/laporan/buku-besar-konsolidasi'
    | '/laporan/buku-besar-pusat'
    | '/laporan/laba-rugi'
    | '/laporan/neraca-konsolidasi'
    | '/laporan/neraca-pusat'
    | '/laporan/rekonsiliasi-rk'
    | '/pengaturan/bagi-hasil'
    | '/pengaturan/users'
    | '/pusat/kegiatan'
    | '/usp/aset'
    | '/usp/jurnal-koreksi'
    | '/usp/kegiatan'
    | '/usp/laporan'
    | '/usp/pinjaman'
    | '/usp/transfer'
    | '/dagang/'
    | '/pengaturan/'
    | '/usp/'
    | '/dagang/kegiatan/beban'
    | '/dagang/kegiatan/belanja-aset'
    | '/dagang/kegiatan/pembayaran-utang'
    | '/dagang/kegiatan/pembelian-kredit'
    | '/dagang/kegiatan/pembelian-tunai'
    | '/dagang/kegiatan/penerimaan-kas'
    | '/dagang/kegiatan/penerimaan-piutang'
    | '/dagang/kegiatan/pengeluaran'
    | '/dagang/kegiatan/penjualan-kredit'
    | '/dagang/kegiatan/penjualan-tunai'
    | '/dagang/laporan/bagi-hasil'
    | '/dagang/laporan/buku-besar'
    | '/dagang/laporan/laba-rugi'
    | '/dagang/laporan/neraca'
    | '/dagang/laporan/rekonsiliasi-rk'
    | '/usp/kegiatan/angsuran'
    | '/usp/kegiatan/beban'
    | '/usp/kegiatan/belanja-aset'
    | '/usp/kegiatan/denda'
    | '/usp/kegiatan/pencairan'
    | '/usp/kegiatan/penerimaan-kas'
    | '/usp/kegiatan/pengeluaran'
    | '/usp/kegiatan/penyertaan-modal'
    | '/usp/laporan/bagi-hasil'
    | '/usp/laporan/buku-besar'
    | '/usp/laporan/laba-rugi'
    | '/usp/laporan/neraca'
    | '/usp/laporan/rekonsiliasi-rk'
    | '/dagang/kegiatan/'
    | '/dagang/laporan/'
    | '/usp/kegiatan/'
    | '/usp/laporan/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/aset'
    | '/catat-kegiatan'
    | '/coa'
    | '/dashboard'
    | '/jurnal-koreksi'
    | '/laporan-pusat'
    | '/transfer-antar-entitas'
    | '/kontak'
    | '/tentang'
    | '/transparansi'
    | '/unit-usaha'
    | '/login/$unit'
    | '/dagang/aset'
    | '/dagang/jurnal-koreksi'
    | '/dagang/stok'
    | '/dagang/transfer'
    | '/laporan/bagi-hasil'
    | '/laporan/buku-besar-konsolidasi'
    | '/laporan/buku-besar-pusat'
    | '/laporan/laba-rugi'
    | '/laporan/neraca-konsolidasi'
    | '/laporan/neraca-pusat'
    | '/laporan/rekonsiliasi-rk'
    | '/pengaturan/bagi-hasil'
    | '/pengaturan/users'
    | '/pusat/kegiatan'
    | '/usp/aset'
    | '/usp/jurnal-koreksi'
    | '/usp/pinjaman'
    | '/usp/transfer'
    | '/dagang'
    | '/pengaturan'
    | '/usp'
    | '/dagang/kegiatan/beban'
    | '/dagang/kegiatan/belanja-aset'
    | '/dagang/kegiatan/pembayaran-utang'
    | '/dagang/kegiatan/pembelian-kredit'
    | '/dagang/kegiatan/pembelian-tunai'
    | '/dagang/kegiatan/penerimaan-kas'
    | '/dagang/kegiatan/penerimaan-piutang'
    | '/dagang/kegiatan/pengeluaran'
    | '/dagang/kegiatan/penjualan-kredit'
    | '/dagang/kegiatan/penjualan-tunai'
    | '/dagang/laporan/bagi-hasil'
    | '/dagang/laporan/buku-besar'
    | '/dagang/laporan/laba-rugi'
    | '/dagang/laporan/neraca'
    | '/dagang/laporan/rekonsiliasi-rk'
    | '/usp/kegiatan/angsuran'
    | '/usp/kegiatan/beban'
    | '/usp/kegiatan/belanja-aset'
    | '/usp/kegiatan/denda'
    | '/usp/kegiatan/pencairan'
    | '/usp/kegiatan/penerimaan-kas'
    | '/usp/kegiatan/pengeluaran'
    | '/usp/kegiatan/penyertaan-modal'
    | '/usp/laporan/bagi-hasil'
    | '/usp/laporan/buku-besar'
    | '/usp/laporan/laba-rugi'
    | '/usp/laporan/neraca'
    | '/usp/laporan/rekonsiliasi-rk'
    | '/dagang/kegiatan'
    | '/dagang/laporan'
    | '/usp/kegiatan'
    | '/usp/laporan'
  id:
    | '__root__'
    | '/_app'
    | '/_public'
    | '/login'
    | '/_app/aset'
    | '/_app/catat-kegiatan'
    | '/_app/coa'
    | '/_app/dagang'
    | '/_app/dashboard'
    | '/_app/jurnal-koreksi'
    | '/_app/laporan-pusat'
    | '/_app/pengaturan'
    | '/_app/transfer-antar-entitas'
    | '/_app/usp'
    | '/_public/kontak'
    | '/_public/tentang'
    | '/_public/transparansi'
    | '/_public/unit-usaha'
    | '/login/$unit'
    | '/_public/'
    | '/_app/dagang/aset'
    | '/_app/dagang/jurnal-koreksi'
    | '/_app/dagang/kegiatan'
    | '/_app/dagang/laporan'
    | '/_app/dagang/stok'
    | '/_app/dagang/transfer'
    | '/_app/laporan/bagi-hasil'
    | '/_app/laporan/buku-besar-konsolidasi'
    | '/_app/laporan/buku-besar-pusat'
    | '/_app/laporan/laba-rugi'
    | '/_app/laporan/neraca-konsolidasi'
    | '/_app/laporan/neraca-pusat'
    | '/_app/laporan/rekonsiliasi-rk'
    | '/_app/pengaturan/bagi-hasil'
    | '/_app/pengaturan/users'
    | '/_app/pusat/kegiatan'
    | '/_app/usp/aset'
    | '/_app/usp/jurnal-koreksi'
    | '/_app/usp/kegiatan'
    | '/_app/usp/laporan'
    | '/_app/usp/pinjaman'
    | '/_app/usp/transfer'
    | '/_app/dagang/'
    | '/_app/pengaturan/'
    | '/_app/usp/'
    | '/_app/dagang/kegiatan/beban'
    | '/_app/dagang/kegiatan/belanja-aset'
    | '/_app/dagang/kegiatan/pembayaran-utang'
    | '/_app/dagang/kegiatan/pembelian-kredit'
    | '/_app/dagang/kegiatan/pembelian-tunai'
    | '/_app/dagang/kegiatan/penerimaan-kas'
    | '/_app/dagang/kegiatan/penerimaan-piutang'
    | '/_app/dagang/kegiatan/pengeluaran'
    | '/_app/dagang/kegiatan/penjualan-kredit'
    | '/_app/dagang/kegiatan/penjualan-tunai'
    | '/_app/dagang/laporan/bagi-hasil'
    | '/_app/dagang/laporan/buku-besar'
    | '/_app/dagang/laporan/laba-rugi'
    | '/_app/dagang/laporan/neraca'
    | '/_app/dagang/laporan/rekonsiliasi-rk'
    | '/_app/usp/kegiatan/angsuran'
    | '/_app/usp/kegiatan/beban'
    | '/_app/usp/kegiatan/belanja-aset'
    | '/_app/usp/kegiatan/denda'
    | '/_app/usp/kegiatan/pencairan'
    | '/_app/usp/kegiatan/penerimaan-kas'
    | '/_app/usp/kegiatan/pengeluaran'
    | '/_app/usp/kegiatan/penyertaan-modal'
    | '/_app/usp/laporan/bagi-hasil'
    | '/_app/usp/laporan/buku-besar'
    | '/_app/usp/laporan/laba-rugi'
    | '/_app/usp/laporan/neraca'
    | '/_app/usp/laporan/rekonsiliasi-rk'
    | '/_app/dagang/kegiatan/'
    | '/_app/dagang/laporan/'
    | '/_app/usp/kegiatan/'
    | '/_app/usp/laporan/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  LoginRoute: typeof LoginRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/login/$unit': {
      id: '/login/$unit'
      path: '/$unit'
      fullPath: '/login/$unit'
      preLoaderRoute: typeof LoginUnitRouteImport
      parentRoute: typeof LoginRoute
    }
    '/_public/unit-usaha': {
      id: '/_public/unit-usaha'
      path: '/unit-usaha'
      fullPath: '/unit-usaha'
      preLoaderRoute: typeof PublicUnitUsahaRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/transparansi': {
      id: '/_public/transparansi'
      path: '/transparansi'
      fullPath: '/transparansi'
      preLoaderRoute: typeof PublicTransparansiRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/tentang': {
      id: '/_public/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof PublicTentangRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/kontak': {
      id: '/_public/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof PublicKontakRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_app/usp': {
      id: '/_app/usp'
      path: '/usp'
      fullPath: '/usp'
      preLoaderRoute: typeof AppUspRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transfer-antar-entitas': {
      id: '/_app/transfer-antar-entitas'
      path: '/transfer-antar-entitas'
      fullPath: '/transfer-antar-entitas'
      preLoaderRoute: typeof AppTransferAntarEntitasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pengaturan': {
      id: '/_app/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof AppPengaturanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/laporan-pusat': {
      id: '/_app/laporan-pusat'
      path: '/laporan-pusat'
      fullPath: '/laporan-pusat'
      preLoaderRoute: typeof AppLaporanPusatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jurnal-koreksi': {
      id: '/_app/jurnal-koreksi'
      path: '/jurnal-koreksi'
      fullPath: '/jurnal-koreksi'
      preLoaderRoute: typeof AppJurnalKoreksiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dagang': {
      id: '/_app/dagang'
      path: '/dagang'
      fullPath: '/dagang'
      preLoaderRoute: typeof AppDagangRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/coa': {
      id: '/_app/coa'
      path: '/coa'
      fullPath: '/coa'
      preLoaderRoute: typeof AppCoaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catat-kegiatan': {
      id: '/_app/catat-kegiatan'
      path: '/catat-kegiatan'
      fullPath: '/catat-kegiatan'
      preLoaderRoute: typeof AppCatatKegiatanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/aset': {
      id: '/_app/aset'
      path: '/aset'
      fullPath: '/aset'
      preLoaderRoute: typeof AppAsetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/usp/': {
      id: '/_app/usp/'
      path: '/'
      fullPath: '/usp/'
      preLoaderRoute: typeof AppUspIndexRouteImport
      parentRoute: typeof AppUspRoute
    }
    '/_app/pengaturan/': {
      id: '/_app/pengaturan/'
      path: '/'
      fullPath: '/pengaturan/'
      preLoaderRoute: typeof AppPengaturanIndexRouteImport
      parentRoute: typeof AppPengaturanRoute
    }
    '/_app/dagang/': {
      id: '/_app/dagang/'
      path: '/'
      fullPath: '/dagang/'
      preLoaderRoute: typeof AppDagangIndexRouteImport
      parentRoute: typeof AppDagangRoute
    }
    '/_app/usp/transfer': {
      id: '/_app/usp/transfer'
      path: '/transfer'
      fullPath: '/usp/transfer'
      preLoaderRoute: typeof AppUspTransferRouteImport
      parentRoute: typeof AppUspRoute
    }
    '/_app/usp/pinjaman': {
      id: '/_app/usp/pinjaman'
      path: '/pinjaman'
      fullPath: '/usp/pinjaman'
      preLoaderRoute: typeof AppUspPinjamanRouteImport
      parentRoute: typeof AppUspRoute
    }
    '/_app/usp/laporan': {
      id: '/_app/usp/laporan'
      path: '/laporan'
      fullPath: '/usp/laporan'
      preLoaderRoute: typeof AppUspLaporanRouteImport
      parentRoute: typeof AppUspRoute
    }
    '/_app/usp/kegiatan': {
      id: '/_app/usp/kegiatan'
      path: '/kegiatan'
      fullPath: '/usp/kegiatan'
      preLoaderRoute: typeof AppUspKegiatanRouteImport
      parentRoute: typeof AppUspRoute
    }
    '/_app/usp/jurnal-koreksi': {
      id: '/_app/usp/jurnal-koreksi'
      path: '/jurnal-koreksi'
      fullPath: '/usp/jurnal-koreksi'
      preLoaderRoute: typeof AppUspJurnalKoreksiRouteImport
      parentRoute: typeof AppUspRoute
    }
    '/_app/usp/aset': {
      id: '/_app/usp/aset'
      path: '/aset'
      fullPath: '/usp/aset'
      preLoaderRoute: typeof AppUspAsetRouteImport
      parentRoute: typeof AppUspRoute
    }
    '/_app/pusat/kegiatan': {
      id: '/_app/pusat/kegiatan'
      path: '/pusat/kegiatan'
      fullPath: '/pusat/kegiatan'
      preLoaderRoute: typeof AppPusatKegiatanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pengaturan/users': {
      id: '/_app/pengaturan/users'
      path: '/users'
      fullPath: '/pengaturan/users'
      preLoaderRoute: typeof AppPengaturanUsersRouteImport
      parentRoute: typeof AppPengaturanRoute
    }
    '/_app/pengaturan/bagi-hasil': {
      id: '/_app/pengaturan/bagi-hasil'
      path: '/bagi-hasil'
      fullPath: '/pengaturan/bagi-hasil'
      preLoaderRoute: typeof AppPengaturanBagiHasilRouteImport
      parentRoute: typeof AppPengaturanRoute
    }
    '/_app/laporan/rekonsiliasi-rk': {
      id: '/_app/laporan/rekonsiliasi-rk'
      path: '/laporan/rekonsiliasi-rk'
      fullPath: '/laporan/rekonsiliasi-rk'
      preLoaderRoute: typeof AppLaporanRekonsiliasiRkRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/laporan/neraca-pusat': {
      id: '/_app/laporan/neraca-pusat'
      path: '/laporan/neraca-pusat'
      fullPath: '/laporan/neraca-pusat'
      preLoaderRoute: typeof AppLaporanNeracaPusatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/laporan/neraca-konsolidasi': {
      id: '/_app/laporan/neraca-konsolidasi'
      path: '/laporan/neraca-konsolidasi'
      fullPath: '/laporan/neraca-konsolidasi'
      preLoaderRoute: typeof AppLaporanNeracaKonsolidasiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/laporan/laba-rugi': {
      id: '/_app/laporan/laba-rugi'
      path: '/laporan/laba-rugi'
      fullPath: '/laporan/laba-rugi'
      preLoaderRoute: typeof AppLaporanLabaRugiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/laporan/buku-besar-pusat': {
      id: '/_app/laporan/buku-besar-pusat'
      path: '/laporan/buku-besar-pusat'
      fullPath: '/laporan/buku-besar-pusat'
      preLoaderRoute: typeof AppLaporanBukuBesarPusatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/laporan/buku-besar-konsolidasi': {
      id: '/_app/laporan/buku-besar-konsolidasi'
      path: '/laporan/buku-besar-konsolidasi'
      fullPath: '/laporan/buku-besar-konsolidasi'
      preLoaderRoute: typeof AppLaporanBukuBesarKonsolidasiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/laporan/bagi-hasil': {
      id: '/_app/laporan/bagi-hasil'
      path: '/laporan/bagi-hasil'
      fullPath: '/laporan/bagi-hasil'
      preLoaderRoute: typeof AppLaporanBagiHasilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dagang/transfer': {
      id: '/_app/dagang/transfer'
      path: '/transfer'
      fullPath: '/dagang/transfer'
      preLoaderRoute: typeof AppDagangTransferRouteImport
      parentRoute: typeof AppDagangRoute
    }
    '/_app/dagang/stok': {
      id: '/_app/dagang/stok'
      path: '/stok'
      fullPath: '/dagang/stok'
      preLoaderRoute: typeof AppDagangStokRouteImport
      parentRoute: typeof AppDagangRoute
    }
    '/_app/dagang/laporan': {
      id: '/_app/dagang/laporan'
      path: '/laporan'
      fullPath: '/dagang/laporan'
      preLoaderRoute: typeof AppDagangLaporanRouteImport
      parentRoute: typeof AppDagangRoute
    }
    '/_app/dagang/kegiatan': {
      id: '/_app/dagang/kegiatan'
      path: '/kegiatan'
      fullPath: '/dagang/kegiatan'
      preLoaderRoute: typeof AppDagangKegiatanRouteImport
      parentRoute: typeof AppDagangRoute
    }
    '/_app/dagang/jurnal-koreksi': {
      id: '/_app/dagang/jurnal-koreksi'
      path: '/jurnal-koreksi'
      fullPath: '/dagang/jurnal-koreksi'
      preLoaderRoute: typeof AppDagangJurnalKoreksiRouteImport
      parentRoute: typeof AppDagangRoute
    }
    '/_app/dagang/aset': {
      id: '/_app/dagang/aset'
      path: '/aset'
      fullPath: '/dagang/aset'
      preLoaderRoute: typeof AppDagangAsetRouteImport
      parentRoute: typeof AppDagangRoute
    }
    '/_app/usp/laporan/': {
      id: '/_app/usp/laporan/'
      path: '/'
      fullPath: '/usp/laporan/'
      preLoaderRoute: typeof AppUspLaporanIndexRouteImport
      parentRoute: typeof AppUspLaporanRoute
    }
    '/_app/usp/kegiatan/': {
      id: '/_app/usp/kegiatan/'
      path: '/'
      fullPath: '/usp/kegiatan/'
      preLoaderRoute: typeof AppUspKegiatanIndexRouteImport
      parentRoute: typeof AppUspKegiatanRoute
    }
    '/_app/dagang/laporan/': {
      id: '/_app/dagang/laporan/'
      path: '/'
      fullPath: '/dagang/laporan/'
      preLoaderRoute: typeof AppDagangLaporanIndexRouteImport
      parentRoute: typeof AppDagangLaporanRoute
    }
    '/_app/dagang/kegiatan/': {
      id: '/_app/dagang/kegiatan/'
      path: '/'
      fullPath: '/dagang/kegiatan/'
      preLoaderRoute: typeof AppDagangKegiatanIndexRouteImport
      parentRoute: typeof AppDagangKegiatanRoute
    }
    '/_app/usp/laporan/rekonsiliasi-rk': {
      id: '/_app/usp/laporan/rekonsiliasi-rk'
      path: '/rekonsiliasi-rk'
      fullPath: '/usp/laporan/rekonsiliasi-rk'
      preLoaderRoute: typeof AppUspLaporanRekonsiliasiRkRouteImport
      parentRoute: typeof AppUspLaporanRoute
    }
    '/_app/usp/laporan/neraca': {
      id: '/_app/usp/laporan/neraca'
      path: '/neraca'
      fullPath: '/usp/laporan/neraca'
      preLoaderRoute: typeof AppUspLaporanNeracaRouteImport
      parentRoute: typeof AppUspLaporanRoute
    }
    '/_app/usp/laporan/laba-rugi': {
      id: '/_app/usp/laporan/laba-rugi'
      path: '/laba-rugi'
      fullPath: '/usp/laporan/laba-rugi'
      preLoaderRoute: typeof AppUspLaporanLabaRugiRouteImport
      parentRoute: typeof AppUspLaporanRoute
    }
    '/_app/usp/laporan/buku-besar': {
      id: '/_app/usp/laporan/buku-besar'
      path: '/buku-besar'
      fullPath: '/usp/laporan/buku-besar'
      preLoaderRoute: typeof AppUspLaporanBukuBesarRouteImport
      parentRoute: typeof AppUspLaporanRoute
    }
    '/_app/usp/laporan/bagi-hasil': {
      id: '/_app/usp/laporan/bagi-hasil'
      path: '/bagi-hasil'
      fullPath: '/usp/laporan/bagi-hasil'
      preLoaderRoute: typeof AppUspLaporanBagiHasilRouteImport
      parentRoute: typeof AppUspLaporanRoute
    }
    '/_app/usp/kegiatan/penyertaan-modal': {
      id: '/_app/usp/kegiatan/penyertaan-modal'
      path: '/penyertaan-modal'
      fullPath: '/usp/kegiatan/penyertaan-modal'
      preLoaderRoute: typeof AppUspKegiatanPenyertaanModalRouteImport
      parentRoute: typeof AppUspKegiatanRoute
    }
    '/_app/usp/kegiatan/pengeluaran': {
      id: '/_app/usp/kegiatan/pengeluaran'
      path: '/pengeluaran'
      fullPath: '/usp/kegiatan/pengeluaran'
      preLoaderRoute: typeof AppUspKegiatanPengeluaranRouteImport
      parentRoute: typeof AppUspKegiatanRoute
    }
    '/_app/usp/kegiatan/penerimaan-kas': {
      id: '/_app/usp/kegiatan/penerimaan-kas'
      path: '/penerimaan-kas'
      fullPath: '/usp/kegiatan/penerimaan-kas'
      preLoaderRoute: typeof AppUspKegiatanPenerimaanKasRouteImport
      parentRoute: typeof AppUspKegiatanRoute
    }
    '/_app/usp/kegiatan/pencairan': {
      id: '/_app/usp/kegiatan/pencairan'
      path: '/pencairan'
      fullPath: '/usp/kegiatan/pencairan'
      preLoaderRoute: typeof AppUspKegiatanPencairanRouteImport
      parentRoute: typeof AppUspKegiatanRoute
    }
    '/_app/usp/kegiatan/denda': {
      id: '/_app/usp/kegiatan/denda'
      path: '/denda'
      fullPath: '/usp/kegiatan/denda'
      preLoaderRoute: typeof AppUspKegiatanDendaRouteImport
      parentRoute: typeof AppUspKegiatanRoute
    }
    '/_app/usp/kegiatan/belanja-aset': {
      id: '/_app/usp/kegiatan/belanja-aset'
      path: '/belanja-aset'
      fullPath: '/usp/kegiatan/belanja-aset'
      preLoaderRoute: typeof AppUspKegiatanBelanjaAsetRouteImport
      parentRoute: typeof AppUspKegiatanRoute
    }
    '/_app/usp/kegiatan/beban': {
      id: '/_app/usp/kegiatan/beban'
      path: '/beban'
      fullPath: '/usp/kegiatan/beban'
      preLoaderRoute: typeof AppUspKegiatanBebanRouteImport
      parentRoute: typeof AppUspKegiatanRoute
    }
    '/_app/usp/kegiatan/angsuran': {
      id: '/_app/usp/kegiatan/angsuran'
      path: '/angsuran'
      fullPath: '/usp/kegiatan/angsuran'
      preLoaderRoute: typeof AppUspKegiatanAngsuranRouteImport
      parentRoute: typeof AppUspKegiatanRoute
    }
    '/_app/dagang/laporan/rekonsiliasi-rk': {
      id: '/_app/dagang/laporan/rekonsiliasi-rk'
      path: '/rekonsiliasi-rk'
      fullPath: '/dagang/laporan/rekonsiliasi-rk'
      preLoaderRoute: typeof AppDagangLaporanRekonsiliasiRkRouteImport
      parentRoute: typeof AppDagangLaporanRoute
    }
    '/_app/dagang/laporan/neraca': {
      id: '/_app/dagang/laporan/neraca'
      path: '/neraca'
      fullPath: '/dagang/laporan/neraca'
      preLoaderRoute: typeof AppDagangLaporanNeracaRouteImport
      parentRoute: typeof AppDagangLaporanRoute
    }
    '/_app/dagang/laporan/laba-rugi': {
      id: '/_app/dagang/laporan/laba-rugi'
      path: '/laba-rugi'
      fullPath: '/dagang/laporan/laba-rugi'
      preLoaderRoute: typeof AppDagangLaporanLabaRugiRouteImport
      parentRoute: typeof AppDagangLaporanRoute
    }
    '/_app/dagang/laporan/buku-besar': {
      id: '/_app/dagang/laporan/buku-besar'
      path: '/buku-besar'
      fullPath: '/dagang/laporan/buku-besar'
      preLoaderRoute: typeof AppDagangLaporanBukuBesarRouteImport
      parentRoute: typeof AppDagangLaporanRoute
    }
    '/_app/dagang/laporan/bagi-hasil': {
      id: '/_app/dagang/laporan/bagi-hasil'
      path: '/bagi-hasil'
      fullPath: '/dagang/laporan/bagi-hasil'
      preLoaderRoute: typeof AppDagangLaporanBagiHasilRouteImport
      parentRoute: typeof AppDagangLaporanRoute
    }
    '/_app/dagang/kegiatan/penjualan-tunai': {
      id: '/_app/dagang/kegiatan/penjualan-tunai'
      path: '/penjualan-tunai'
      fullPath: '/dagang/kegiatan/penjualan-tunai'
      preLoaderRoute: typeof AppDagangKegiatanPenjualanTunaiRouteImport
      parentRoute: typeof AppDagangKegiatanRoute
    }
    '/_app/dagang/kegiatan/penjualan-kredit': {
      id: '/_app/dagang/kegiatan/penjualan-kredit'
      path: '/penjualan-kredit'
      fullPath: '/dagang/kegiatan/penjualan-kredit'
      preLoaderRoute: typeof AppDagangKegiatanPenjualanKreditRouteImport
      parentRoute: typeof AppDagangKegiatanRoute
    }
    '/_app/dagang/kegiatan/pengeluaran': {
      id: '/_app/dagang/kegiatan/pengeluaran'
      path: '/pengeluaran'
      fullPath: '/dagang/kegiatan/pengeluaran'
      preLoaderRoute: typeof AppDagangKegiatanPengeluaranRouteImport
      parentRoute: typeof AppDagangKegiatanRoute
    }
    '/_app/dagang/kegiatan/penerimaan-piutang': {
      id: '/_app/dagang/kegiatan/penerimaan-piutang'
      path: '/penerimaan-piutang'
      fullPath: '/dagang/kegiatan/penerimaan-piutang'
      preLoaderRoute: typeof AppDagangKegiatanPenerimaanPiutangRouteImport
      parentRoute: typeof AppDagangKegiatanRoute
    }
    '/_app/dagang/kegiatan/penerimaan-kas': {
      id: '/_app/dagang/kegiatan/penerimaan-kas'
      path: '/penerimaan-kas'
      fullPath: '/dagang/kegiatan/penerimaan-kas'
      preLoaderRoute: typeof AppDagangKegiatanPenerimaanKasRouteImport
      parentRoute: typeof AppDagangKegiatanRoute
    }
    '/_app/dagang/kegiatan/pembelian-tunai': {
      id: '/_app/dagang/kegiatan/pembelian-tunai'
      path: '/pembelian-tunai'
      fullPath: '/dagang/kegiatan/pembelian-tunai'
      preLoaderRoute: typeof AppDagangKegiatanPembelianTunaiRouteImport
      parentRoute: typeof AppDagangKegiatanRoute
    }
    '/_app/dagang/kegiatan/pembelian-kredit': {
      id: '/_app/dagang/kegiatan/pembelian-kredit'
      path: '/pembelian-kredit'
      fullPath: '/dagang/kegiatan/pembelian-kredit'
      preLoaderRoute: typeof AppDagangKegiatanPembelianKreditRouteImport
      parentRoute: typeof AppDagangKegiatanRoute
    }
    '/_app/dagang/kegiatan/pembayaran-utang': {
      id: '/_app/dagang/kegiatan/pembayaran-utang'
      path: '/pembayaran-utang'
      fullPath: '/dagang/kegiatan/pembayaran-utang'
      preLoaderRoute: typeof AppDagangKegiatanPembayaranUtangRouteImport
      parentRoute: typeof AppDagangKegiatanRoute
    }
    '/_app/dagang/kegiatan/belanja-aset': {
      id: '/_app/dagang/kegiatan/belanja-aset'
      path: '/belanja-aset'
      fullPath: '/dagang/kegiatan/belanja-aset'
      preLoaderRoute: typeof AppDagangKegiatanBelanjaAsetRouteImport
      parentRoute: typeof AppDagangKegiatanRoute
    }
    '/_app/dagang/kegiatan/beban': {
      id: '/_app/dagang/kegiatan/beban'
      path: '/beban'
      fullPath: '/dagang/kegiatan/beban'
      preLoaderRoute: typeof AppDagangKegiatanBebanRouteImport
      parentRoute: typeof AppDagangKegiatanRoute
    }
  }
}

interface AppDagangKegiatanRouteChildren {
  AppDagangKegiatanBebanRoute: typeof AppDagangKegiatanBebanRoute
  AppDagangKegiatanBelanjaAsetRoute: typeof AppDagangKegiatanBelanjaAsetRoute
  AppDagangKegiatanPembayaranUtangRoute: typeof AppDagangKegiatanPembayaranUtangRoute
  AppDagangKegiatanPembelianKreditRoute: typeof AppDagangKegiatanPembelianKreditRoute
  AppDagangKegiatanPembelianTunaiRoute: typeof AppDagangKegiatanPembelianTunaiRoute
  AppDagangKegiatanPenerimaanKasRoute: typeof AppDagangKegiatanPenerimaanKasRoute
  AppDagangKegiatanPenerimaanPiutangRoute: typeof AppDagangKegiatanPenerimaanPiutangRoute
  AppDagangKegiatanPengeluaranRoute: typeof AppDagangKegiatanPengeluaranRoute
  AppDagangKegiatanPenjualanKreditRoute: typeof AppDagangKegiatanPenjualanKreditRoute
  AppDagangKegiatanPenjualanTunaiRoute: typeof AppDagangKegiatanPenjualanTunaiRoute
  AppDagangKegiatanIndexRoute: typeof AppDagangKegiatanIndexRoute
}

const AppDagangKegiatanRouteChildren: AppDagangKegiatanRouteChildren = {
  AppDagangKegiatanBebanRoute: AppDagangKegiatanBebanRoute,
  AppDagangKegiatanBelanjaAsetRoute: AppDagangKegiatanBelanjaAsetRoute,
  AppDagangKegiatanPembayaranUtangRoute: AppDagangKegiatanPembayaranUtangRoute,
  AppDagangKegiatanPembelianKreditRoute: AppDagangKegiatanPembelianKreditRoute,
  AppDagangKegiatanPembelianTunaiRoute: AppDagangKegiatanPembelianTunaiRoute,
  AppDagangKegiatanPenerimaanKasRoute: AppDagangKegiatanPenerimaanKasRoute,
  AppDagangKegiatanPenerimaanPiutangRoute:
    AppDagangKegiatanPenerimaanPiutangRoute,
  AppDagangKegiatanPengeluaranRoute: AppDagangKegiatanPengeluaranRoute,
  AppDagangKegiatanPenjualanKreditRoute: AppDagangKegiatanPenjualanKreditRoute,
  AppDagangKegiatanPenjualanTunaiRoute: AppDagangKegiatanPenjualanTunaiRoute,
  AppDagangKegiatanIndexRoute: AppDagangKegiatanIndexRoute,
}

const AppDagangKegiatanRouteWithChildren =
  AppDagangKegiatanRoute._addFileChildren(AppDagangKegiatanRouteChildren)

interface AppDagangLaporanRouteChildren {
  AppDagangLaporanBagiHasilRoute: typeof AppDagangLaporanBagiHasilRoute
  AppDagangLaporanBukuBesarRoute: typeof AppDagangLaporanBukuBesarRoute
  AppDagangLaporanLabaRugiRoute: typeof AppDagangLaporanLabaRugiRoute
  AppDagangLaporanNeracaRoute: typeof AppDagangLaporanNeracaRoute
  AppDagangLaporanRekonsiliasiRkRoute: typeof AppDagangLaporanRekonsiliasiRkRoute
  AppDagangLaporanIndexRoute: typeof AppDagangLaporanIndexRoute
}

const AppDagangLaporanRouteChildren: AppDagangLaporanRouteChildren = {
  AppDagangLaporanBagiHasilRoute: AppDagangLaporanBagiHasilRoute,
  AppDagangLaporanBukuBesarRoute: AppDagangLaporanBukuBesarRoute,
  AppDagangLaporanLabaRugiRoute: AppDagangLaporanLabaRugiRoute,
  AppDagangLaporanNeracaRoute: AppDagangLaporanNeracaRoute,
  AppDagangLaporanRekonsiliasiRkRoute: AppDagangLaporanRekonsiliasiRkRoute,
  AppDagangLaporanIndexRoute: AppDagangLaporanIndexRoute,
}

const AppDagangLaporanRouteWithChildren =
  AppDagangLaporanRoute._addFileChildren(AppDagangLaporanRouteChildren)

interface AppDagangRouteChildren {
  AppDagangAsetRoute: typeof AppDagangAsetRoute
  AppDagangJurnalKoreksiRoute: typeof AppDagangJurnalKoreksiRoute
  AppDagangKegiatanRoute: typeof AppDagangKegiatanRouteWithChildren
  AppDagangLaporanRoute: typeof AppDagangLaporanRouteWithChildren
  AppDagangStokRoute: typeof AppDagangStokRoute
  AppDagangTransferRoute: typeof AppDagangTransferRoute
  AppDagangIndexRoute: typeof AppDagangIndexRoute
}

const AppDagangRouteChildren: AppDagangRouteChildren = {
  AppDagangAsetRoute: AppDagangAsetRoute,
  AppDagangJurnalKoreksiRoute: AppDagangJurnalKoreksiRoute,
  AppDagangKegiatanRoute: AppDagangKegiatanRouteWithChildren,
  AppDagangLaporanRoute: AppDagangLaporanRouteWithChildren,
  AppDagangStokRoute: AppDagangStokRoute,
  AppDagangTransferRoute: AppDagangTransferRoute,
  AppDagangIndexRoute: AppDagangIndexRoute,
}

const AppDagangRouteWithChildren = AppDagangRoute._addFileChildren(
  AppDagangRouteChildren,
)

interface AppPengaturanRouteChildren {
  AppPengaturanBagiHasilRoute: typeof AppPengaturanBagiHasilRoute
  AppPengaturanUsersRoute: typeof AppPengaturanUsersRoute
  AppPengaturanIndexRoute: typeof AppPengaturanIndexRoute
}

const AppPengaturanRouteChildren: AppPengaturanRouteChildren = {
  AppPengaturanBagiHasilRoute: AppPengaturanBagiHasilRoute,
  AppPengaturanUsersRoute: AppPengaturanUsersRoute,
  AppPengaturanIndexRoute: AppPengaturanIndexRoute,
}

const AppPengaturanRouteWithChildren = AppPengaturanRoute._addFileChildren(
  AppPengaturanRouteChildren,
)

interface AppUspKegiatanRouteChildren {
  AppUspKegiatanAngsuranRoute: typeof AppUspKegiatanAngsuranRoute
  AppUspKegiatanBebanRoute: typeof AppUspKegiatanBebanRoute
  AppUspKegiatanBelanjaAsetRoute: typeof AppUspKegiatanBelanjaAsetRoute
  AppUspKegiatanDendaRoute: typeof AppUspKegiatanDendaRoute
  AppUspKegiatanPencairanRoute: typeof AppUspKegiatanPencairanRoute
  AppUspKegiatanPenerimaanKasRoute: typeof AppUspKegiatanPenerimaanKasRoute
  AppUspKegiatanPengeluaranRoute: typeof AppUspKegiatanPengeluaranRoute
  AppUspKegiatanPenyertaanModalRoute: typeof AppUspKegiatanPenyertaanModalRoute
  AppUspKegiatanIndexRoute: typeof AppUspKegiatanIndexRoute
}

const AppUspKegiatanRouteChildren: AppUspKegiatanRouteChildren = {
  AppUspKegiatanAngsuranRoute: AppUspKegiatanAngsuranRoute,
  AppUspKegiatanBebanRoute: AppUspKegiatanBebanRoute,
  AppUspKegiatanBelanjaAsetRoute: AppUspKegiatanBelanjaAsetRoute,
  AppUspKegiatanDendaRoute: AppUspKegiatanDendaRoute,
  AppUspKegiatanPencairanRoute: AppUspKegiatanPencairanRoute,
  AppUspKegiatanPenerimaanKasRoute: AppUspKegiatanPenerimaanKasRoute,
  AppUspKegiatanPengeluaranRoute: AppUspKegiatanPengeluaranRoute,
  AppUspKegiatanPenyertaanModalRoute: AppUspKegiatanPenyertaanModalRoute,
  AppUspKegiatanIndexRoute: AppUspKegiatanIndexRoute,
}

const AppUspKegiatanRouteWithChildren = AppUspKegiatanRoute._addFileChildren(
  AppUspKegiatanRouteChildren,
)

interface AppUspLaporanRouteChildren {
  AppUspLaporanBagiHasilRoute: typeof AppUspLaporanBagiHasilRoute
  AppUspLaporanBukuBesarRoute: typeof AppUspLaporanBukuBesarRoute
  AppUspLaporanLabaRugiRoute: typeof AppUspLaporanLabaRugiRoute
  AppUspLaporanNeracaRoute: typeof AppUspLaporanNeracaRoute
  AppUspLaporanRekonsiliasiRkRoute: typeof AppUspLaporanRekonsiliasiRkRoute
  AppUspLaporanIndexRoute: typeof AppUspLaporanIndexRoute
}

const AppUspLaporanRouteChildren: AppUspLaporanRouteChildren = {
  AppUspLaporanBagiHasilRoute: AppUspLaporanBagiHasilRoute,
  AppUspLaporanBukuBesarRoute: AppUspLaporanBukuBesarRoute,
  AppUspLaporanLabaRugiRoute: AppUspLaporanLabaRugiRoute,
  AppUspLaporanNeracaRoute: AppUspLaporanNeracaRoute,
  AppUspLaporanRekonsiliasiRkRoute: AppUspLaporanRekonsiliasiRkRoute,
  AppUspLaporanIndexRoute: AppUspLaporanIndexRoute,
}

const AppUspLaporanRouteWithChildren = AppUspLaporanRoute._addFileChildren(
  AppUspLaporanRouteChildren,
)

interface AppUspRouteChildren {
  AppUspAsetRoute: typeof AppUspAsetRoute
  AppUspJurnalKoreksiRoute: typeof AppUspJurnalKoreksiRoute
  AppUspKegiatanRoute: typeof AppUspKegiatanRouteWithChildren
  AppUspLaporanRoute: typeof AppUspLaporanRouteWithChildren
  AppUspPinjamanRoute: typeof AppUspPinjamanRoute
  AppUspTransferRoute: typeof AppUspTransferRoute
  AppUspIndexRoute: typeof AppUspIndexRoute
}

const AppUspRouteChildren: AppUspRouteChildren = {
  AppUspAsetRoute: AppUspAsetRoute,
  AppUspJurnalKoreksiRoute: AppUspJurnalKoreksiRoute,
  AppUspKegiatanRoute: AppUspKegiatanRouteWithChildren,
  AppUspLaporanRoute: AppUspLaporanRouteWithChildren,
  AppUspPinjamanRoute: AppUspPinjamanRoute,
  AppUspTransferRoute: AppUspTransferRoute,
  AppUspIndexRoute: AppUspIndexRoute,
}

const AppUspRouteWithChildren =
  AppUspRoute._addFileChildren(AppUspRouteChildren)

interface AppRouteChildren {
  AppAsetRoute: typeof AppAsetRoute
  AppCatatKegiatanRoute: typeof AppCatatKegiatanRoute
  AppCoaRoute: typeof AppCoaRoute
  AppDagangRoute: typeof AppDagangRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppJurnalKoreksiRoute: typeof AppJurnalKoreksiRoute
  AppLaporanPusatRoute: typeof AppLaporanPusatRoute
  AppPengaturanRoute: typeof AppPengaturanRouteWithChildren
  AppTransferAntarEntitasRoute: typeof AppTransferAntarEntitasRoute
  AppUspRoute: typeof AppUspRouteWithChildren
  AppLaporanBagiHasilRoute: typeof AppLaporanBagiHasilRoute
  AppLaporanBukuBesarKonsolidasiRoute: typeof AppLaporanBukuBesarKonsolidasiRoute
  AppLaporanBukuBesarPusatRoute: typeof AppLaporanBukuBesarPusatRoute
  AppLaporanLabaRugiRoute: typeof AppLaporanLabaRugiRoute
  AppLaporanNeracaKonsolidasiRoute: typeof AppLaporanNeracaKonsolidasiRoute
  AppLaporanNeracaPusatRoute: typeof AppLaporanNeracaPusatRoute
  AppLaporanRekonsiliasiRkRoute: typeof AppLaporanRekonsiliasiRkRoute
  AppPusatKegiatanRoute: typeof AppPusatKegiatanRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAsetRoute: AppAsetRoute,
  AppCatatKegiatanRoute: AppCatatKegiatanRoute,
  AppCoaRoute: AppCoaRoute,
  AppDagangRoute: AppDagangRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppJurnalKoreksiRoute: AppJurnalKoreksiRoute,
  AppLaporanPusatRoute: AppLaporanPusatRoute,
  AppPengaturanRoute: AppPengaturanRouteWithChildren,
  AppTransferAntarEntitasRoute: AppTransferAntarEntitasRoute,
  AppUspRoute: AppUspRouteWithChildren,
  AppLaporanBagiHasilRoute: AppLaporanBagiHasilRoute,
  AppLaporanBukuBesarKonsolidasiRoute: AppLaporanBukuBesarKonsolidasiRoute,
  AppLaporanBukuBesarPusatRoute: AppLaporanBukuBesarPusatRoute,
  AppLaporanLabaRugiRoute: AppLaporanLabaRugiRoute,
  AppLaporanNeracaKonsolidasiRoute: AppLaporanNeracaKonsolidasiRoute,
  AppLaporanNeracaPusatRoute: AppLaporanNeracaPusatRoute,
  AppLaporanRekonsiliasiRkRoute: AppLaporanRekonsiliasiRkRoute,
  AppPusatKegiatanRoute: AppPusatKegiatanRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PublicRouteChildren {
  PublicKontakRoute: typeof PublicKontakRoute
  PublicTentangRoute: typeof PublicTentangRoute
  PublicTransparansiRoute: typeof PublicTransparansiRoute
  PublicUnitUsahaRoute: typeof PublicUnitUsahaRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicKontakRoute: PublicKontakRoute,
  PublicTentangRoute: PublicTentangRoute,
  PublicTransparansiRoute: PublicTransparansiRoute,
  PublicUnitUsahaRoute: PublicUnitUsahaRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface LoginRouteChildren {
  LoginUnitRoute: typeof LoginUnitRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginUnitRoute: LoginUnitRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  LoginRoute: LoginRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
